%it is sucessful.
%consider amplitude error and phase error of channel 
%the error is generated by stochastic
clear;  close all
%initial and generate  data of signal
D=5; M=32; M1=29; M2=M-M1; aperture=0.5;
N=100;
randn('seed',17)
Aerror=0.00; %幅度误差     
Perror=0; %相位误差
Fold_error=(1+Aerror*randn(M,1)).*exp(i*pi*Perror*randn(M,1)/180); %总误差
Mainfold=diag(Fold_error);
X1=interfer(M,N); 
%X2=target(M);
%Y=zeros(M2,N);
X=X1;   %+X2;%X=X1+[X2;Y];
X=Mainfold*X1;
%end of data

%seperate main channel data and 3 auxiliary channel data
X=conj(X');
sidelobe=35;
weight_m=chebwin(M1,sidelobe);
% weight_m=-Wbayliss(M1,sidelobe);
% nsll =-25;  nlevel=5;  Wdow=talor_win(nsll,nlevel,M1);   weight_m=Wdow.';
main_X=X(:,1:M1);  side_X=X(:,(M1+1):M);
main_syn=main_X*weight_m+1.*(randn(N,1)+0*i*randn(N,1));  
Alfa=10^(-10/20);                  %主辅天线幅度相差分贝数
weight_s=Alfa*sum(weight_m)*10^(-sidelobe/20);
% weight_s=0.8;
side_X=weight_s.*side_X+1.*(randn(N,M2)+0*i*randn(N,M2));

side_X=conj(side_X');%1

%caculate R and R0
R=side_X*side_X'/N;
%R=R+1000*eye(M2);      %diagnoal loading have no good effect
%R=cov(conj(side_X'));  %function cov() have question
main_syn=conj(main_syn);
R0=side_X*main_syn/N;
%caculate the Wopt
Wopt_s=inv(R)*R0;

%Draw driection picture
Wopt_es=-weight_s.*Wopt_s;
Wopt=[weight_m;Wopt_es];   %乘一系数对结果无影响
angel=-90:90;
Fq=pattern_error(weight_m,M1,aperture,Mainfold(1:M1,1:M1));   Fq=abs(Fq);   
Fa=pattern_error(Wopt_es,M2,aperture,Mainfold(M1+1:M,M1+1:M));    Fa=abs(Fa);   
Fs=pattern_error(Wopt,M,aperture,Mainfold);        Fs=abs(Fs);      
Fmax=max([Fq,Fa,Fs]);  
Fq=20*log10(Fq/Fmax);   Fa=20*log10(Fa/Fmax);   Fs=20*log10(Fs/Fmax);
figure(1);  hold on;   grid;    axis([-100 100 -120 0]);
% plot(angel,Fq,'g');
% plot(angel,Fa,'g--');
plot(angel,Fs,'r','lineWidth',2);  hold on
xlabel('方向 (度)' );  ylabel('增益（dB）');  title('自适应零点波瓣图');  axis([-90 90 -120 0])

Wopt_s;
%The last result has some question;
%'+'and'-'is in contrast.   

%用于对消的数据
N=(M-M1)*1000;
X1=interfer(M,N);
X=X1;   %+X2;%X=X1+[X2;Y];
X=Mainfold*X1;
%seperate main channel data and 3 auxiliary channel data
X=conj(X');
main_X=X(:,1:M1);  side_X=X(:,(M1+1):M);
main_syn=main_X*weight_m+1.*(randn(N,1)+0*i*randn(N,1));  
side_X=weight_s.*side_X+1.*(randn(N,M2)+0*i*randn(N,M2));
side_X=conj(side_X');    main_syn=conj(main_syn);

Ji=conj(main_syn);%restore main_syn
Ji=conj(Ji');
Jo=Wopt_s'*side_X;
remain=Ji-Jo;
PJi=10*log10(Ji*Ji'/N);
PJo=10*log10(remain*remain'/N);
Gp=PJi-PJo;
Result=[PJi,PJo,Gp]
%figure(2)
%plot(abs(remain))


